import type { SiteSchema } from '@modernizer/schema'
import type { PromptParts } from '../llm-client.js'
import { DESIGN_SYSTEM_FILE_PATH } from '../design-system.js'
import { buildSiteContextBlock } from './shared.js'

/**
 * Builds the prompt for the shared shell: root layout, navbar, footer, plus a design-tokens
 * hand-off note. Every page.tsx is generated by a separate, independent Claude call that never
 * sees this call's output — without an explicit hand-off, each page call ends up inventing its
 * own spacing/card/heading/button conventions from scratch, so pages stop looking like one site.
 * This call decides those conventions once and writes them to DESIGN_SYSTEM_FILE_PATH, which
 * index.ts extracts (see design-system.ts) and threads into every page prompt.
 */
export const buildShellPrompt = (schema: SiteSchema): PromptParts => ({
  cached: buildSiteContextBlock(schema),
  task: `You are building the shared shell (root layout, navbar, footer) for this site, and defining the visual design system every other page will be required to follow exactly.

## Required Files
Generate exactly these four outputs:
- src/app/layout.tsx — root layout rendering <Navbar /> and <Footer /> around {children}, imports './globals.css', sets \`metadata\` (title: site name, description: tagline or site name)
- src/components/layout/Navbar.tsx — sticky/fixed navbar. It must stay fully visible at all times, including on page load before any scroll or hover — do NOT hide, fade, or rely on a hover/focus state to reveal the nav links or their container; a subtle shadow appearing on scroll is fine, but the links themselves are always visible. Use the Navigation above (already local route paths — use \`next/link\`), with a mobile menu.
  If any nav item has children (a dropdown submenu), the trigger and its dropdown panel must share one continuous hoverable region with NO gap between them — do not offset the panel from the trigger with an outer margin (e.g. \`mt-2\` on the panel itself), since that creates a dead zone the cursor crosses while covering nothing, firing \`onMouseLeave\` and closing the menu before the user reaches the submenu items. Instead keep the panel flush against the trigger (\`top-full\`, no margin) and add any visual spacing as padding *inside* the panel (e.g. \`pt-2\` on its inner content), so the hoverable hit-box has zero gap.
- src/components/layout/Footer.tsx — footer using the site info and contact details above
- ${DESIGN_SYSTEM_FILE_PATH} — NOT part of the Next.js app (do not import it from anywhere, do not use App Router file conventions for it) — a single JSON object (no markdown, no code fences, no prose outside the object) recording the exact visual conventions you used above, as literal Tailwind utility class strings a different engineer could copy verbatim into unrelated files and get a matching look. It must have exactly this shape, every key required:
  \`\`\`
  {
    "container": string,            // page container width + horizontal padding, e.g. "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"
    "sectionSpacing": {
      "hero": string,                // hero section py-* classes
      "standard": string,            // standard content section py-* classes
      "compact": string              // compact/utility section py-* classes
    },
    "card": string,                 // corner radius, border/shadow treatment, hover state, as one class string
    "headingScale": {
      "hero": string,                // hero heading text-*/font-* classes
      "section": string,             // section heading text-*/font-* classes
      "sub": string                  // sub-heading text-*/font-* classes
    },
    "buttons": {
      "primary": string,             // shadcn Button variant/size for primary CTAs
      "secondary": string            // shadcn Button variant/size for secondary CTAs
    },
    "heroTreatment": string,        // background style (image overlay direction/opacity, or solid/gradient), text alignment, min-height
    "iconPresentation": string,     // container shape/size/background if icons are boxed, or bare sizing if not
    "hoverTransition": string,      // hover/transition convention used throughout, e.g. "transition-colors duration-200"
    "gridLayouts": string,          // column counts + gap classes for 2/3/4-column grids
    "commonPatterns": string        // recurring layout idioms not covered above (e.g. centered section intros, vertical stack spacing)
  }
  \`\`\`
  Do NOT repeat theme color token guidance here (\`bg-primary\`, \`bg-card\`, etc.) — that's already covered in the Tech Stack section above.
  Be specific enough that reusing these exact strings elsewhere reproduces the same look — vague guidance like "generous spacing" is not useful here.

Do NOT generate any page.tsx files — those are generated separately, in their own requests, and will be told to follow the design system above exactly.

Call write_files with these four outputs.`,
})
